services:
  # A Docker web service
  - type: web
    name: webdis
    env: docker
    repo: https://github.com/Nneji123/flask-client-camera.git # optional
    region: oregon # optional (defaults to oregon)
    plan: standard # optional (defaults to starter)
    branch: main # optional (defaults to master)
    rootDir: webdis
    # dockerCommand: ./webdis.sh # optional (defaults to Dockerfile command)
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /
